spring.datasource.url=jdbc:postgresql://ec2-18-215-111-67.compute-1.amazonaws.com:5432/d4c1r91ntgpr0j
spring.datasource.username=qdrcifmoyggakn
spring.datasource.password=b1a4de4ce47cc065298f53b65aaf8f5aca1375ec52dc44962eee79bb9018af54
spring.jpa.show-sql=true

#Hiberneate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

#Hibernate Properties
#The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
spring.jpa.properties.hibernate.format_sql=true